In [31]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([1.0, 2.0], requires_grad=True)

# Use the tensor in a simple operation
y = x * 2

# first element of y must be 10

y2 = y - (y +10)* torch.tensor([1,0])


# Compute a loss and backward
loss = torch.prod(y2)
loss.backward()

print(x.grad)  # Gradients for x


tensor([  0., -20.])


In [3]:
import numpy as np
np.exp(20)

485165195.4097903

In [39]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([1.0, 2.0], requires_grad=True)

y = torch.where(torch.tensor([True, False]), 10., x)

# Compute a loss and backward
loss = torch.prod(torch.exp(y))
loss.backward()

print(x.grad)  # Gradients for x


tensor([     0.0000, 162754.7812])


In [40]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([10.0, 2.0], requires_grad=True)
y = x.clone()

# Compute a loss and backward
loss = torch.prod(torch.exp(y))
loss.backward()

print(x.grad)  # Gradients for x


tensor([162754.7812, 162754.7812])


In [49]:
import torch

# Create a tensor with requires_grad=True
x = torch.nn.Parameter(torch.tensor([5.0, 2.0]))
w = torch.tensor([3., 4.])
# Use the tensor in a simple operation
mask = torch.tensor([1, 0], dtype=torch.bool)
x.data = torch.where(mask, 1., x)
loss = x @ w

loss.backward()
print(x.grad)


tensor([3., 4.])


In [57]:
import torch

# Create a tensor with requires_grad=True
x = torch.nn.Parameter(torch.tensor([5.0, 2.0]))
w = torch.tensor([3., 4.])
# Use the tensor in a simple operation
mask = torch.tensor([True, False])
x2 = x * ~mask + mask*1.0
loss = torch.exp(x2 @ w)

loss.backward()
print(x.grad)


tensor([     0.0000, 239496.5625])


In [58]:
import torch

# Create a tensor with requires_grad=True
x = torch.nn.Parameter(torch.tensor([1.0, 2.0]))
w = torch.tensor([3., 4.])
# Use the tensor in a simple operation
loss = torch.exp(x @ w)

loss.backward()
print(x.grad)


tensor([179622.4219, 239496.5625])


In [48]:
import torch

# Create a tensor with requires_grad=True
x = torch.nn.Parameter(torch.tensor([1.0, 2.0]))
w = torch.tensor([3., 4.])
# Use the tensor in a simple operation
loss = x @ w

loss.backward()
print(x.grad)


tensor([3., 4.])


In [32]:
import torch

# Create a tensor with requires_grad=True
x = torch.nn.Parameter(torch.tensor([5.0, 2.0], requires_grad=True))
w = torch.tensor([3., 4.])

# Use the tensor in a simple operation
mask = torch.tensor([1, 0], dtype=torch.bool)
x.data[mask] = 1.  # Modify in-place

loss = x @ w
loss.backward()

print(x.grad)
print(w.grad)


tensor([3., 4.])
None


In [60]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.param = nn.Parameter(torch.tensor([5.0, 2.0]))

        # Register backward hook
        self.param.register_hook(self.zero_grad_hook)

    def zero_grad_hook(self, grad):
        # Set the gradient of the first element to 0
        grad[0] = 0.
        return grad

    def forward(self, x):
        # ... some computation ...
        return x * self.param

# Example usage
model = MyModel()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

x = torch.tensor([3.0, 4.0])
output = model(x)
loss = output.sum()
loss.backward()

optimizer.step()
print(model.param)  # Only the second element should be updated


Parameter containing:
tensor([5.0000, 1.9600], requires_grad=True)


In [23]:

# Create a mask indicating which elements to change
mask = torch.tensor([1, 0], dtype=torch.bool)

# Using torch.where to apply the mask
y_fixed = torch.where(mask, 10., y)

# Compute a loss and backward
loss = torch.prod(y_fixed)
loss.backward()

print(x.grad)  # Gradients for x


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.